name: KonspiracyStudios
favicon: null
layout_spectrum: 0.43411053461022675
typography_spectrum: 0.2851168846245855
title: Konspiracy Studios
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5c6c9'
    - '#424a4e'
    - '#101010'
    - '#7792a7'
    - '#8e6d60'
  brandStrength: 0.944718062877655
  lightness: 0.9006767079699785
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
