name: KonspiracyStudios
favicon: null
layout_spectrum: 0.43411053461022675
typography_spectrum: 0.2851168846245855
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.944718062877655
  lightness: 0.9006767079699785
  saturation: 0.12013174057938159
  rhythmicContrast: 0.15250593051314354
purpose: []
